ALTER TABLE "Post"
ADD COLUMN "section" TEXT NOT NULL DEFAULT 'general';

UPDATE "Post"
SET "section" = CASE
    WHEN LOWER(COALESCE("title", '') || ' ' || COALESCE("content", '')) LIKE '%osu%'
      OR LOWER(COALESCE("title", '') || ' ' || COALESCE("content", '')) LIKE '%osu!%'
      OR LOWER(COALESCE("title", '') || ' ' || COALESCE("content", '')) LIKE '%mania%'
      OR LOWER(COALESCE("title", '') || ' ' || COALESCE("content", '')) LIKE '%taiko%'
      OR LOWER(COALESCE("title", '') || ' ' || COALESCE("content", '')) LIKE '%catch%'
      OR COALESCE("title", '') || ' ' || COALESCE("content", '') LIKE '%谱面%'
      OR COALESCE("title", '') || ' ' || COALESCE("content", '') LIKE '%作图%'
      OR COALESCE("title", '') || ' ' || COALESCE("content", '') LIKE '%打图%'
      OR COALESCE("title", '') || ' ' || COALESCE("content", '') LIKE '%圆盘%'
        THEN 'osu'
    WHEN LOWER(COALESCE("title", '') || ' ' || COALESCE("content", '')) LIKE '%maimai%'
      OR LOWER(COALESCE("title", '') || ' ' || COALESCE("content", '')) LIKE '% dx%'
      OR COALESCE("title", '') || ' ' || COALESCE("content", '') LIKE '%舞萌%'
      OR COALESCE("title", '') || ' ' || COALESCE("content", '') LIKE '%机厅%'
      OR COALESCE("title", '') || ' ' || COALESCE("content", '') LIKE '%街机%'
      OR COALESCE("title", '') || ' ' || COALESCE("content", '') LIKE '%段位%'
        THEN 'maimai'
    WHEN LOWER(COALESCE("title", '') || ' ' || COALESCE("content", '')) LIKE '%project sekai%'
      OR LOWER(COALESCE("title", '') || ' ' || COALESCE("content", '')) LIKE '%sekai%'
      OR LOWER(COALESCE("title", '') || ' ' || COALESCE("content", '')) LIKE '%pjsk%'
      OR COALESCE("title", '') || ' ' || COALESCE("content", '') LIKE '%世界计划%'
      OR COALESCE("title", '') || ' ' || COALESCE("content", '') LIKE '%初音未来缤纷舞台%'
      OR LOWER(COALESCE("title", '') || ' ' || COALESCE("content", '')) LIKE '%leo/need%'
        THEN 'pjsk'
    WHEN LOWER(COALESCE("title", '') || ' ' || COALESCE("content", '')) LIKE '%arcaea%'
      OR COALESCE("title", '') || ' ' || COALESCE("content", '') LIKE '%光与对立%'
      OR COALESCE("title", '') || ' ' || COALESCE("content", '') LIKE '%定数%'
      OR COALESCE("title", '') || ' ' || COALESCE("content", '') LIKE '%搭档%'
      OR COALESCE("title", '') || ' ' || COALESCE("content", '') LIKE '%曲包%'
        THEN 'arcaea'
    WHEN COALESCE("title", '') || ' ' || COALESCE("content", '') LIKE '%比赛%'
      OR COALESCE("title", '') || ' ' || COALESCE("content", '') LIKE '%赛事%'
      OR COALESCE("title", '') || ' ' || COALESCE("content", '') LIKE '%活动%'
      OR COALESCE("title", '') || ' ' || COALESCE("content", '') LIKE '%面基%'
      OR COALESCE("title", '') || ' ' || COALESCE("content", '') LIKE '%约玩%'
      OR COALESCE("title", '') || ' ' || COALESCE("content", '') LIKE '%招募%'
      OR COALESCE("title", '') || ' ' || COALESCE("content", '') LIKE '%线下%'
      OR COALESCE("title", '') || ' ' || COALESCE("content", '') LIKE '%展会%'
        THEN 'event'
    ELSE 'general'
END;
